import type { ArticleMap } from "../src/types/article";

export const articles: ArticleMap[] = [
	{
		id: "1000",
		title: "緊急クエスト",
		route: "/緊急クエスト",
		parentId: [],
		genres: ["緊急クエスト"],
	},
	{
		id: "1001",
		title: "緊急C",
		route: "/緊急クエスト/緊急C",
		parentId: ["1000"],
		genres: ["緊急クエスト", "緊急C"],
	},
	{
		id: "1010",
		title: "[緊急C] 原っぱの探索",
		parentId: ["1000", "1001"],
		route: "/緊急クエスト/原っぱの探索",
		genres: ["緊急クエスト", "緊急C"],
	},
	{
		id: "1011",
		title: "[緊急C] 発芽",
		parentId: ["1000", "1001"],
		route: "/緊急クエスト/発芽",
		genres: ["緊急クエスト", "緊急C"],
	},
	{
		id: "1002",
		title: "緊急B",
		route: "/緊急クエスト/緊急B",
		parentId: ["1000"],
		genres: ["緊急クエスト", "緊急B"],
	},
	{
		id: "1020",
		title: "[緊急B] 海岸の防衛線",
		parentId: ["1000", "1002"],
		route: "/緊急クエスト/海岸の防衛線",
		genres: ["緊急クエスト", "緊急B"],
	},
	{
		id: "1021",
		title: "[緊急B] 妖精舞踏",
		parentId: ["1000", "1002"],
		route: "/緊急クエスト/妖精舞踏",
		genres: ["緊急クエスト", "緊急B"],
	},
	{
		id: "1022",
		title: "[緊急B] 茂みの探索",
		parentId: ["1000", "1002"],
		route: "/緊急クエスト/茂みの探索",
		genres: ["緊急クエスト", "緊急B"],
	},
	{
		id: "1023",
		title: "[緊急B] 浜辺の探索",
		parentId: ["1000", "1002"],
		route: "/緊急クエスト/浜辺の探索",
		genres: ["緊急クエスト", "緊急B"],
	},
	{
		id: "1024",
		title: "[緊急B] 平原の疾走",
		parentId: ["1000", "1002"],
		route: "/緊急クエスト/平原の疾走",
		genres: ["緊急クエスト", "緊急B"],
	},
	{
		id: "1025",
		title: "[緊急B] 燃えさかる妖狐",
		parentId: ["1000", "1002"],
		route: "/緊急クエスト/燃えさかる妖狐",
		genres: ["緊急クエスト", "緊急B"],
	},
	{
		id: "1026",
		title: "[緊急B] 雑草の戯れ",
		parentId: ["1000", "1002"],
		route: "/緊急クエスト/雑草の戯れ",
		genres: ["緊急クエスト", "緊急B"],
	},
	{
		id: "1027",
		title: "[緊急B] 森の探索",
		parentId: ["1000", "1002"],
		route: "/緊急クエスト/森の探索",
		genres: ["緊急クエスト", "緊急B"],
	},
	{
		id: "1028",
		title: "[緊急B] 妖怪集結",
		parentId: ["1000", "1002"],
		route: "/緊急クエスト/妖怪集結",
		genres: ["緊急クエスト", "緊急B"],
	},
	{
		id: "1029",
		title: "[緊急B] ゆらめく妖気",
		parentId: ["1000", "1002"],
		route: "/緊急クエスト/ゆらめく妖気",
		genres: ["緊急クエスト", "緊急B"],
	},
	{
		id: "1003",
		title: "緊急A",
		route: "/緊急クエスト/緊急A",
		parentId: ["1000"],
		genres: ["緊急クエスト", "緊急A"],
	},
	{
		id: "1030",
		title: "[緊急A] 果て無き荒野",
		parentId: ["1000", "1003"],
		route: "/緊急クエスト/果て無き荒野",
		genres: ["緊急クエスト", "緊急A"],
	},
	{
		id: "1031",
		title: "[緊急A] 侵蝕の原っぱ",
		parentId: ["1000", "1003"],
		route: "/緊急クエスト/侵蝕の原っぱ",
		genres: ["緊急クエスト", "緊急A"],
	},
	{
		id: "1032",
		title: "[緊急A] 魔菌地帯",
		parentId: ["1000", "1003"],
		route: "/緊急クエスト/魔菌地帯",
		genres: ["緊急クエスト", "緊急A"],
	},
	{
		id: "1004",
		title: "緊急S",
		route: "/緊急クエスト/緊急S",
		parentId: ["1000"],
		genres: ["緊急クエスト", "緊急S"],
	},
	{
		id: "1040",
		title: "[緊急S] 黄金を求めて",
		parentId: ["1000", "1004"],
		route: "/緊急クエスト/黄金を求めて",
		genres: ["緊急クエスト", "緊急S"],
	},
	{
		id: "1041",
		title: "[緊急S] 魔界の生物",
		parentId: ["1000", "1004"],
		route: "/緊急クエスト/魔界の生物",
		genres: ["緊急クエスト", "緊急S"],
	},
	{
		id: "1042",
		title: "[緊急S] 伝説の木",
		parentId: ["1000", "1004"],
		route: "/緊急クエスト/伝説の木",
		genres: ["緊急クエスト", "緊急S"],
	}
];
